name: Publish to Packagist

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Packagist Webhook
        run: |
          curl -X POST -d 'repository_url=https://github.com/globiguard/globiguard-php' \
            "https://packagist.org/api/update-package?username=globiguard&apiToken=${{ secrets.PACKAGIST_TOKEN }}"
