name: Test & Lint

on:
  push:
    branches: [ sol, main, develop ]
  pull_request:
    branches: [ sol, main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Run tests
        run: composer validate --strict
